### ISSUE TITLE
Require Bootstrap.js

### ISSUE THREAD

**Issue by njdart** [bag-man/nodestack#12]
```footer.pug``` currently does not include the bootstrap js file. This is required for dropdowns (among other things);

```pug
script(src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
```

In addition bootstrap provides integrity hash which should be used for both the js and css [because we're getting the resources from a CDN](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

```pug
script(src='...' integrity='sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa' crossorigin='anonymous')

**Comment by bag-man** [comment]
Just saw this, PR it fool :P
